// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYRMmtPzjtguk08SS7s8dwaq0XTB0Gfk',
    appId: '1:195345094314:web:1af1caefd87c73a9d722d3',
    messagingSenderId: '195345094314',
    projectId: 'bysirvandad2',
    authDomain: 'bysirvandad2.firebaseapp.com',
    storageBucket: 'bysirvandad2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfDlDEibZqydcd-nGXz2Fv3HVxK2yfoJk',
    appId: '1:195345094314:android:769b05c3264e78b6d722d3',
    messagingSenderId: '195345094314',
    projectId: 'bysirvandad2',
    storageBucket: 'bysirvandad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv48eoaV62efE_FZrKnJbUqjTptbLz-4Y',
    appId: '1:195345094314:ios:a6ebaf863de3d658d722d3',
    messagingSenderId: '195345094314',
    projectId: 'bysirvandad2',
    storageBucket: 'bysirvandad2.firebasestorage.app',
    iosBundleId: 'com.example.firebasenotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv48eoaV62efE_FZrKnJbUqjTptbLz-4Y',
    appId: '1:195345094314:ios:a6ebaf863de3d658d722d3',
    messagingSenderId: '195345094314',
    projectId: 'bysirvandad2',
    storageBucket: 'bysirvandad2.firebasestorage.app',
    iosBundleId: 'com.example.firebasenotesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYRMmtPzjtguk08SS7s8dwaq0XTB0Gfk',
    appId: '1:195345094314:web:b8c3de079355d3a0d722d3',
    messagingSenderId: '195345094314',
    projectId: 'bysirvandad2',
    authDomain: 'bysirvandad2.firebaseapp.com',
    storageBucket: 'bysirvandad2.firebasestorage.app',
  );
}
